routes/web.php
    Route::resource('catUes', 'CatUeController')->except('show');
    Route::resource('ues', 'UeController')->except('show');

    Route::get('notes/search/{n}/{type?}', 'NoteController@search')->name('notes.search');
    // Routes pour l'enregistrement des notes
    Route::get('notes/affiche/{semestre}/{specialite}', 'NoteController@affiche')->name('notes.affiche');
    Route::get('notes/afficheNotesDouala/{semestre}/{specialite}', 'NoteController@afficheNotesDouala')->name('notes.afficheNotesDouala');
    Route::get('notes/afficheNotesYaounde/{semestre}/{specialite}', 'NoteController@afficheNotesYaounde')->name('notes.afficheNotesYaounde');

    Route::get('notes/imprime/{semestre}/{specialite}', 'NoteController@imprime')->name('notes.imprime');
    Route::get('notes/releve/{session}/{contrat}/{semestre}', 'NoteController@releve')->name('notes.releve');
    Route::get('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@a_deliberer')->name('notes.a_deliberer');
    Route::post('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@pv')->name('notes.pv');

    Route::get('notes/pvcc/{specialite}/{semestre}', 'NoteController@pvcc')->name('notes.pvcc');
    Route::get('notes/pvccDla/{specialite}/{semestre}', 'NoteController@pvcc_dla')->name('notes.pvcc_dla');
    Route::get('notes/pvccYde/{specialite}/{semestre}', 'NoteController@pvcc_yde')->name('notes.pvcc_yde');

    Route::get('notes/rn_intermediaire/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaire')->name('notes.rn_intermediaire');
    Route::get('notes/rn_intermediaireDouala/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireDouala')->name('notes.rn_intermediaireDouala');
    Route::get('notes/rn_intermediaireYaounde/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireYaounde')->name('notes.rn_intermediaireYaounde');

    Route::resource('notes', 'NoteController')->except('store', 'show');

    Route::get('notes/show/{type}/{id}', 'NoteController@show')->name('notes.show');
    Route::get('notes/showDouala/{type}/{id}', 'NoteController@showDouala')->name('notes.showDouala');
    Route::get('notes/showYaounde/{type}/{id}', 'NoteController@showYaounde')->name('notes.showYaounde');
    
    Route::post('notes/{type}/{enseignement}', 'NoteController@store')->name('notes.store');
    // Enregistrer les notes de Douala
    Route::post('notes1/{type}/{enseignement}', 'NoteController@storeDouala')->name('notes.storeDouala');
    // Enregistrer les notes de Yaoundé
    Route::post('notes2/{type}/{enseignement}', 'NoteController@storeYaounde')->name('notes.storeYaounde');

    

    Route::get('notes/deliberation/{semestre}/{specialite}', 'NoteController@deliberation')->name('notes.deliberation');
    Route::get('notes/notesDeliberation/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberation')->name('notes.noteDeliberation');
    // Enregistrer la note de délibération
    Route::post('notes/deliberation/{semestre}/{type}/{contrat}', 'NoteController@saveDeliberation')->name('notes.saveDeliberation');
    /*
        Séparer les notes de délibération de Douala et Yaoundé
        Route::get('notes/deliberationDouala/{semestre}/{specialite}', 'NoteController@deliberationDouala')->name('notes.deliberationDouala');
        Route::get('notes/notesDeliberationDouala/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationDouala')->name('notes.noteDeliberationDouala');

        Route::get('notes/deliberationYaounde/{semestre}/{specialite}', 'NoteController@deliberationYaounde')->name('notes.deliberationYaounde');
        Route::get('notes/notesDeliberationYaounde/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationYaounde')->name('notes.noteDeliberationYaounde');
    */

    Route::get('notes/getNoteContrat/{contrat}/{enseignement}', 'NoteController@getNoteContrat')->name('notes.getNoteContrat');

    Route::get('notes/rattrapage/{semestre}/{specialite}', 'NoteController@rattrapage')->name('notes.rattrapage');
    // Routes fiche de notation Douala
    Route::get('notes/fiche/{semestre}/{specialite}', 'NoteController@fiche')->name('notes.fiche');
    Route::get('notes/fiche/{semestre}/{specialite}/{id}', 'NoteController@ficheNotationCC')->name('notes.fiche-notation');

    // Routes fiche de notation Yaoundé
    Route::get('notes/ficheYaounde/{semestre}/{specialite}', 'NoteController@ficheYaounde')->name('notes.ficheYaounde');
    Route::get('notes/ficheYaounde/{semestre}/{specialite}/{id}', 'NoteController@ficheNotationCCYaounde')->name('notes.fiche-notation-yaounde');

    Route::get('versements/listeApprenants', 'VersementController@listeApprenants')->name('versements.listeApprenants');
    Route::get('versements/etats', 'VersementController@etats')->name('versements.etats');
    Route::get('versements/details/{id}', 'VersementController@details')->name('versements.details');
    Route::post('versements/{id}', 'VersementController@store')->name('versements.store');
    Route::get('versements/show/{id}', 'VersementController@show')->name('versements.show');
    Route::get('versements/{id}/edit', 'VersementController@edit')->name('versements.edit');
    Route::patch('versements/{id}/update', 'VersementController@update')->name('versements.update');
    Route::delete('versements/destroy/{id}', 'VersementController@destroy')->name('versements.destroy');


    Route::resource('echeanciers', 'EcheancierController');

    Route::get('moratoires/create/{id}', 'MoratoireController@create')->name('moratoires.create');
    Route::post('moratoires/{id}', 'MoratoireController@store')->name('moratoires.store');
    Route::get('moratoires', 'MoratoireController@index')->name('moratoires.index');
    Route::get('moratoires/{id}/edit', 'MoratoireController@edit')->name('moratoires.edit');
    Route::patch('moratoires/{id}', 'MoratoireController@update')->name('moratoires.update');

    Route::get('scolarites', 'ScolariteController@index')->name('scolarites.index');
    Route::get('scolarites/old', 'ScolariteController@old')->name('scolarites.old');
    Route::get('scolarites/inscrits', 'ScolariteController@inscrits')->name('scolarites.inscrits');
    Route::post('scolarites/filter', 'ScolariteController@filter')->name('scolarites.filter');

    Route::get('rnr', function () {
        return view('notes.rnr_imprime');
    });
    Route::get('certificat/{type}', function ($type) {
        return view('documents.certificat')->with(['type' => $type]);
    });
    Route::get('scolarites/contrats/{id}', 'ScolariteController@contrats')->name('scolarites.contrat');
    Route::get('scolarites/attestation/{contrat}/{type}', 'ScolariteController@attestation')->name('scolarites.attestation');
    Route::get('scolarites/certificat/{contrat}/{type}', 'ScolariteController@certificat')->name('scolarites.certificat');
    Route::get('scolarites/autorisation/{id}', 'ScolariteController@autorisation')->name('scolarites.autorisation');
    Route::get('scolarites/suspension/{id}', 'ScolariteController@suspension')->name('scolarites.suspension');
    Route::get('scolarites/printSuspension', 'ScolariteController@printSuspension')->name('scolarites.printSuspension');
    Route::post('scolarites/printSuspension', 'ScolariteController@suspensions')->name('scolarites.suspensions');

    Route::get('scolarites/attestations/search/{n}', 'ScolariteController@search')->name('scolarites.search'); // pour selectionner la classe a imprimer
    Route::get('scolarites/attestations/select/{cycle}/{specialite}', 'ScolariteController@select_admis')->name('scolarites.select_admis');
    Route::post('scolarites/attestations_reussite', 'ScolariteController@attestations_reussite')->name('scolarites.attestations_reussite');

    Route::get('resultatNominatifs/search/{n}', 'ResultatNominatifController@search')->name('resultatNominatifs.search');
    Route::get('resultatNominatifs/create/{specialite}/{cycle}', 'ResultatNominatifController@create')->name('resultatNominatifs.create');
    Route::post('resultatNominatifs', 'ResultatNominatifController@store')->name('resultatNominatifs.store');

    //    Route::post('notes/{enseignement}/{contrat}', 'NoteController@store')->name('notes.store');

    Route::resource('academicYears', 'AcademicYearController');

    Route::resource('contratEnseignants', 'ContratEnseignantController')->except('show');
    Route::get('contratsEnseignants/all', 'ContratEnseignantController@all')->name('contratEnseignants.all');
    Route::post('contratEnseignants/filter', 'ContratEnseignantController@filter')->name('contratEnseignants.filter');
    Route::get('contratEnseignants/versements/{id}', 'ContratEnseignantController@versements')->name('contratEnseignants.versements');
    Route::post('contratEnseignants/versements/{id}/{type?}', 'ContratEnseignantController@save')->name('contratEnseignants.save');
    Route::get('contratEnseignants/rapport/{id}', 'ContratEnseignantController@rapport')->name('contratEnseignants.rapport');
    Route::get('contratEnseignants/contrats/{id}', 'ContratEnseignantController@contrat')->name('contratEnseignants.contrat');
    Route::get('contratEnseignants/details/{id}', 'ContratEnseignantController@details')->name('contratEnseignants.details');
    Route::get('contratEnseignants/{id}/edit_payment', 'ContratEnseignantController@edit_payment')->name('contratEnseignants.edit_payment');
    Route::delete('contratEnseignants/delete/{id}', 'ContratEnseignantController@delete_payment')->name('contratEnseignants.delete_payment');
    Route::patch('contratEnseignants/update_payment/{id}', 'ContratEnseignantController@update_payment')->name('contratEnseignants.update_payment');



    Route::resource('academicCalendars', 'AcademicCalendarController');

    Route::resource('corkages', 'CorkageController')->except('create');
    Route::get('corkages/create/{id}', 'CorkageController@create')->name('corkages.create');

    // 02/08/2021
    Route::resource('pays', 'PaysController');

app/Models/AcademicYear.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AcademicYear extends Model
{
    protected $fillable = [
        'debut', 'fin', 'actif'
    ];

    public function apprenants(){
        return $this->hasMany(Apprenant::class);
    }

    public function contrats(){
        return $this->hasMany(Apprenant::class);
    }

    public function enseignements(){
        return $this->hasMany(Enseignement::class);
    }

    public function ecues(){
        return $this->hasMany(Ecue::class);
    }
}

app/Http/Controllers/AcademicYearController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\AcademicYearRepository;
use Illuminate\Http\Request;

class AcademicYearController extends Controller
{
    protected $academicYearRepository;

    public function __construct(AcademicYearRepository $academicYearRepository)
    {
        $this->academicYearRepository = $academicYearRepository;
    }

    public function index(){
        $academicYears = $this->academicYearRepository->all();
        return view('academicYears.index', compact('academicYears'));
    }

    public function create(){
        return view('academicYears.create');
    }

    public function store(Request $request){
        if ($request->input('actif')){
            $actif = $this->academicYearRepository->findWhere(['actif' => true])->first();
            $actif->actif = false;
            $actif->save();
        }
        $academicYear = $this->academicYearRepository->updateOrCreate([
            'debut'=>$request->input('debut')
        ],$request->all());

        return redirect()->route('academicYears.index');
    }

    public function activate($id){
        $academicYear = $this->academicYearRepository->findWithoutFail($id);
    }

    public function edit($id){
        $academicYear = $this->academicYearRepository->findWithoutFail($id);
        return view('academicYears.create', compact('academicYear'));
    }

}

resources/views/academicYears/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Academic Year
        </h1>
    </section>
    <div class="row container">
        <div class="content">
            @include('adminlte-templates::common.errors')

            {!! Form::open(['route' => 'academicYears.store', 'id' => 'form']) !!}

            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="form-group col-sm-4">
                            {!! Form::label('debut', 'Année de debut :') !!}
                            {!! Form::text('debut', isset($academicYear) ? $academicYear->debut : null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group col-sm-4">
                            {!! Form::label('fin', 'Année de fin') !!}
                            {!! Form::text('fin', isset($academicYear) ? $academicYear->fin : null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group col-sm-4">
                            {!! Form::label('actif', 'Année en cours?') !!}
                            {!! Form::select('actif', [1 => 'Oui',0 => 'Non'], isset($academicYear) ? $academicYear->actif : null, ['class' => 'form-control', 'placeholder' => '--- Votre choix ---']) !!}
                        </div>

                    </div>
                </div>
                <div class="box-footer">
                    <div class="pull-right">
                        {!! Form::submit('Enregistrer', ['class' => 'btn btn-primary']) !!}
                        <a href="{!! route('academicYears.index') !!}" class="btn btn-default">Annuler</a>
                    </div>
                </div>
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/academicYears/index.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Liste des Moratoires
        </h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('academicYears.create') !!}">Ajouter <i class="fa fa-plus"></i></a>
        </h1>
    </section>

    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="box box-primary">
            <div class="box-body">
                <div class="">
                    <table class="table table-bordered table-responsive" id="academic-table">
                        <thead>
                        <tr>
                            <th>Année academique</th>
                            <th>En cours</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($academicYears as $academicYear)
                            <tr>
                                <td>{!! $academicYear->debut. '/' .$academicYear->fin !!}</td>
                                <td>{{ ($academicYear->actif) ? 'Oui' : 'Non' }}</td>
                                <td>
                                    <a href="{{ route('academicYears.edit', $academicYear->id) }}" class="btn btn-primary" title="ajouter"><i class="fa fa-pencil"></i></a>
{{--                                    <a href="#" class="btn btn-warning" title="modifier"><i class="fa fa-pencil"></i></a>--}}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jq-3.3.1/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/b-print-1.5.6/datatables.min.js"></script>

    <script>
        $(document).ready(function() {
            var table = $('#academic-table').DataTable({
                responsive: true,
                dom:'Blfrtip',
                buttons:[
                    'copy', 'excel', 'pdf'
                ],
                "columnDefs":[
                    {"orderable":false, "targets":1}
                ]
            });

            table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container() ))

        });
    </script>
@endsection

@section('css')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-3.3.1/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/b-print-1.5.6/datatables.min.css"/>
@endsection