routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::prefix('admin')->namespace('Back')->group(function () { 
    Route::name('admin')->get('/', 'AdminController@index');
});
Route::prefix('')->middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('home', 'HomeController@index');
    Route::get('absences/updateJustif/{justification}/{absence}', ['middleware' => 'permission:edit absences', 'uses' => 'AbsenceController@justif'])->name('absences.updateJustif');

    Route::get('absences/updateJustif/{justification}/{absence}', ['middleware' => 'permission:edit absences', 'uses' => 'AbsenceController@updateJustif'])->name('absences.updateJustif');

    Route::get('absences/search/{n}', ['middleware' => 'permission:create absences|read absences|read enseignements', 'uses' => 'AbsenceController@search'])->name('absences.search');
    Route::get('absences/etat', 'AbsenceController@etat')->name('absences.etat');

    Route::get('absences/affiche/{semestre}/{specialite}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@affiche'])->name('absences.affiche');

    Route::get('absences/afficheDouala/{semestre}/{specialite}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@afficheDouala'])->name('absences.afficheDouala');

    Route::get('absences/afficheYaounde/{semestre}/{specialite}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@afficheYaounde'])->name('absences.afficheYaounde');

    Route::get('absences/create/{semestre}/{specialite}', ['middleware' => 'permission:create absences', 'uses' => 'AbsenceController@create'])->name('absences.create');

    Route::get('absences/createDouala/{semestre}/{specialite}', ['middleware' => 'permission:create absences', 'uses' => 'AbsenceController@createDouala'])->name('absences.createDouala');

    Route::get('absences/createYaounde/{semestre}/{specialite}', ['middleware' => 'permission:create absences', 'uses' => 'AbsenceController@createYaounde'])->name('absences.createYaounde');

    Route::get('absences/ficheDouala/{semestre}/{specialite}', 'AbsenceController@ficheDouala')->name('absences.ficheDouala');

    Route::get('absences/ficheDouala/{semestre}/{specialite}/{id}', 'AbsenceController@ficheEcueDouala')->name('absences.fiche-ecue-douala');

    Route::get('absences/ficheYaounde/{semestre}/{specialite}', 'AbsenceController@ficheYaounde')->name('absences.ficheYaounde');

    Route::get('absences/ficheYaounde/{semestre}/{specialite}/{id}', 'AbsenceController@ficheEcueYaounde')->name('absences.fiche-ecue-yaounde');

    Route::get('absences/{apprenant}/edit/{semestre}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@edit'])->name('absences.edit');

    //    Route::get('absence/afficheData, AbsenceController@afficheData')->name('absences.afficheData');
    Route::resource('absences', 'AbsenceController')->except('create', 'edit', 'show');

    Route::name('specialites.getData')->get('specialites/getData', 'SpecialiteController@getData');

    Route::resource('semestres', 'SemestreController');

    Route::get('contrats/all', 'ContratController@all')->name('contrats.all');
    Route::resource('contrats', 'ContratController');

    Route::get('ecues/{id}/getEcues', 'EcueController@getEcues');
    Route::resource('ecues', 'EcueController');

    Route::resource('cycles', 'CycleController');

    Route::resource('apprenants', 'ApprenantController');

    Route::resource('specialites', 'SpecialiteController');

    Route::resource('enseignants', 'EnseignantController');

    Route::get('tutors/{id}', 'TutorController@index')->name('tutors.index');
    Route::get('tutors/create/{id}', 'TutorController@create')->name('tutors.create');
    Route::post('tutors/{id}', 'TutorController@store')->name('tutors.store');
    Route::resource('tutors', 'TutorController')->only('edit', 'update', 'destroy');

    Route::resource('enseignements', 'EnseignementController')->except('create');
    Route::get('enseignements/affiche/{semestre}/{specialite}', 'EnseignementController@affiche')->name('enseignements.affiche');
    Route::get('enseignements/afficheDouala/{semestre}/{specialite}', 'EnseignementController@afficheDouala')->name('enseignements.afficheDouala');
    Route::get('enseignements/afficheYaounde/{semestre}/{specialite}', 'EnseignementController@afficheYaounde')->name('enseignements.afficheYaounde');

    Route::get('enseignements/search/{n}', 'EnseignementController@search')->name('enseignements.search');
    Route::patch('enseignements/{specialites}/updateMh', 'EnseignementController@updateMh')->name('enseignements.updateMh');
    Route::get('enseignements/{specialite}/editMh', 'EnseignementController@editMh')->name('enseignements.editMh');
    Route::get('enseignements/create/{semestre}/{specialite}', 'EnseignementController@create')->name('enseignements.create');
    Route::get('enseignements/rapport/{n}', 'EnseignementController@rapport')->name('rapport');

    // Afficher les fiches d'autorisation de paiement
    Route::get('enseignements/autorisation-paiement/{id}', 'EnseignementController@autorisationPaiement')->name('enseignements.autorisation-paiement');

    //    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('users', 'UserController');

    Route::get('absences/test', 'AbsenceController@test');

    Route::resource('catUes', 'CatUeController')->except('show');
    Route::resource('ues', 'UeController')->except('show');

    Route::get('notes/search/{n}/{type?}', 'NoteController@search')->name('notes.search');
    // Routes pour l'enregistrement des notes
    Route::get('notes/affiche/{semestre}/{specialite}', 'NoteController@affiche')->name('notes.affiche');
    Route::get('notes/afficheNotesDouala/{semestre}/{specialite}', 'NoteController@afficheNotesDouala')->name('notes.afficheNotesDouala');
    Route::get('notes/afficheNotesYaounde/{semestre}/{specialite}', 'NoteController@afficheNotesYaounde')->name('notes.afficheNotesYaounde');

    Route::get('notes/imprime/{semestre}/{specialite}', 'NoteController@imprime')->name('notes.imprime');
    Route::get('notes/releve/{session}/{contrat}/{semestre}', 'NoteController@releve')->name('notes.releve');
    Route::get('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@a_deliberer')->name('notes.a_deliberer');
    Route::post('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@pv')->name('notes.pv');

    Route::get('notes/pvcc/{specialite}/{semestre}', 'NoteController@pvcc')->name('notes.pvcc');
    Route::get('notes/pvccDla/{specialite}/{semestre}', 'NoteController@pvcc_dla')->name('notes.pvcc_dla');
    Route::get('notes/pvccYde/{specialite}/{semestre}', 'NoteController@pvcc_yde')->name('notes.pvcc_yde');

    Route::get('notes/rn_intermediaire/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaire')->name('notes.rn_intermediaire');
    Route::get('notes/rn_intermediaireDouala/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireDouala')->name('notes.rn_intermediaireDouala');
    Route::get('notes/rn_intermediaireYaounde/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireYaounde')->name('notes.rn_intermediaireYaounde');

    Route::resource('notes', 'NoteController')->except('store', 'show');

    Route::get('notes/show/{type}/{id}', 'NoteController@show')->name('notes.show');
    Route::get('notes/showDouala/{type}/{id}', 'NoteController@showDouala')->name('notes.showDouala');
    Route::get('notes/showYaounde/{type}/{id}', 'NoteController@showYaounde')->name('notes.showYaounde');
    
    Route::post('notes/{type}/{enseignement}', 'NoteController@store')->name('notes.store');
    // Enregistrer les notes de Douala
    Route::post('notes1/{type}/{enseignement}', 'NoteController@storeDouala')->name('notes.storeDouala');
    // Enregistrer les notes de Yaoundé
    Route::post('notes2/{type}/{enseignement}', 'NoteController@storeYaounde')->name('notes.storeYaounde');

    

    Route::get('notes/deliberation/{semestre}/{specialite}', 'NoteController@deliberation')->name('notes.deliberation');
    Route::get('notes/notesDeliberation/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberation')->name('notes.noteDeliberation');
    // Enregistrer la note de délibération
    Route::post('notes/deliberation/{semestre}/{type}/{contrat}', 'NoteController@saveDeliberation')->name('notes.saveDeliberation');
    /*
        Séparer les notes de délibération de Douala et Yaoundé
        Route::get('notes/deliberationDouala/{semestre}/{specialite}', 'NoteController@deliberationDouala')->name('notes.deliberationDouala');
        Route::get('notes/notesDeliberationDouala/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationDouala')->name('notes.noteDeliberationDouala');

        Route::get('notes/deliberationYaounde/{semestre}/{specialite}', 'NoteController@deliberationYaounde')->name('notes.deliberationYaounde');
        Route::get('notes/notesDeliberationYaounde/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationYaounde')->name('notes.noteDeliberationYaounde');
    */

    Route::get('notes/getNoteContrat/{contrat}/{enseignement}', 'NoteController@getNoteContrat')->name('notes.getNoteContrat');

    Route::get('notes/rattrapage/{semestre}/{specialite}', 'NoteController@rattrapage')->name('notes.rattrapage');
    // Routes fiche de notation Douala

app/Models/Ecue.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Ecue
 * @package App\Models
 * @version November 28, 2017, 10:58 am UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection Absence
 * @property \App\Models\Semestre semestre
 * @property \Illuminate\Database\Eloquent\Collection ecueSpecialite
 * @property string title
 * @property integer semestre_id
 * @property string slug
 */
class Ecue extends Model
{
    use SoftDeletes;

    public $table = 'ecues';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'title',
        'semestre_id',
        'slug',
        'credits',
        'academic_year_id',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'title' => 'string',
        'semestre_id' => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'bail|required',
        'semestre_id' => 'bail|required|',
        'academic_year_id' => 'bail|required|',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function absences()
    {
        return $this->hasMany(\App\Models\Absence::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function semestre()
    {
        return $this->belongsTo(\App\Models\Semestre::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function specialites()
    {
        return $this->belongsToMany(\App\Models\Specialite::class, 'ecue_specialites');
    }

    public function enseignements()
    {
        return $this->hasMany(\App\Models\Enseignement::class);
    }

    public function academicYear(){
        return $this->belongsTo(AcademicYear::class);
    }
}

resources/views/ecues/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ecue
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="">
                    {!! Form::open(['route' => 'ecues.store']) !!}

                        {{--@include('ecues.fields')--}}
                        <div class="form-group col-xs-4">
                            {!! Form::label('academic_year_id', 'Année Académique:') !!}
                            {!! Form::select('academic_year_id',$academicYears, isset($apprenant)? $apprenant->academic_year_id : null, ['class' => 'form-control', 'placeholder' => 'selectioner l\'année']) !!}
                        </div>

                        <div class="form-group col-md-4">
                            {!! Form::label('title', 'Title:') !!}
                            {!! Form::text('title', null, ['class' => 'form-control', 'id' => 'ecue', 'disabled']) !!}
                        </div>

                        <div class="form-group col-md-4">
                            {!! Form::label('semestre_id', 'Semestre') !!}
                            {!! Form::select('semestre_id', $semestres, null, ['class' => 'form-control', 'disabled']) !!}
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading"><strong>Specialite</strong></div>
                            <div class="panel-body">
                                <ul class="form-group list-group">
                                    @foreach($specialites as $specialite)
                                        <li class="list-group-item">
                                            <label class="checkbox-inline">
                                                {{--{!! Form::hidden('cycle', false) !!}--}}
                                                <label class="checkbox-inline">
                                                    {{--{!! Form::hidden('cycle', false) !!}--}}

                                                    {!! Form::checkbox('specialite[]', $specialite->id,null) !!}
                                                    {!! Form::label($specialite->title,$specialite->title. ' - ' .$specialite->slug)!!}

                                                </label>

                                            </label>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                            <a href="{!! route('ecues.index') !!}" class="btn btn-default">Cancel</a>
                        </div>


                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')

    <link rel="stylesheet" href="{{ url('css/easy-autocomplete.min.css') }}">

@endsection

@section('scripts')
    <script src="{{ url('js/jquery.easy-autocomplete.min.js') }}"></script>
    <script type="text/javascript">
        $(function(){
            var ecues = {!! $ecues !!};
            var title = null
            $("#academic_year_id").change(function () {
                var ay = $("#academic_year_id").val()
                if (ay !='') {
                    $("#ecue, #semestre_id").attr('disabled', false)
                    var url = 'http://' + window.location.host + '/public/ecues/' + ay + '/getEcues'
                    $.ajax({
                        url: url,
                        type: 'get',
                        success: (data, status) => {
                            ecues = data
                            title = {
                                data: ecues,
                                getValue: function (e) {
                                    return e.title
                                },
                                list: {
                                    match: {
                                        enabled: true
                                    },
                                    onClickEvent: function (e) {

                                        var id = $('#ecue').getSelectedItemData().id;
                                        window.location.href = 'http://' + window.location.host + '/ecues/' + id + '/edit';
                                    }
                                }
                            };

                            console.log(title)

                            $('#ecue').easyAutocomplete(title);
                        }
                    })
                }
                else {
                    $("#ecue, #semestre_id").attr('disabled', true)
                }
            })
        });
    </script>

@endsection

resources/views/ecues/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ecue
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="">
                   {!! Form::model($ecue, ['route' => ['ecues.update', $ecue->id], 'method' => 'patch']) !!}

                        @include('ecues.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ecues/fields.blade.php
<!-- Title Field -->
<div class="form-group col-md-4">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-md-4">
    {!! Form::label('semestre_id', 'Semestre') !!}
    {!! Form::select('semestre_id', $semestres, $semestreEcue, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-xs-4">
    {!! Form::label('academic_year_id', 'Année Académique:') !!}
    {!! Form::select('academic_year_id',$academicYears, isset($apprenant)? $apprenant->academic_year_id : null, ['class' => 'form-control', 'placeholder' => 'selectioner l\'année']) !!}
</div>

<div class="panel panel-default ">
    <div class="panel-heading"><strong>Specialite</strong></div>
    <div class="panel-body">
        <ul class="form-group list-group">
            @foreach($specialites as $specialite)
                <li class="list-group-item">
                    <label class="checkbox-inline">
                        {{--{!! Form::hidden('cycle', false) !!}--}}
                        <label class="checkbox-inline">
                            {{--{!! Form::hidden('cycle', false) !!}--}}

                            {!! Form::checkbox('specialite[]', $specialite->id,$ecue->specialites->find($specialite->id),['id' => $specialite->title]) !!}
                            {!! Form::label($specialite->title,$specialite->title. ' - ' .$specialite->slug )!!}

                        </label>

                    </label>
                </li>
            @endforeach
        </ul>
    </div>
</div>

<!-- Submit Field -->
<div class="form-group col-md-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('ecues.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/ecues/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Ecues</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('ecues.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('ecues.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

@section('scripts')

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/datatables.min.js"></script>
    <script type="text/javascript">
//            $(".search").keyup(function () {
//                var searchTerm = $(".search").val();
//                var listItem = $('.results tbody').children('tr');
//                var searchSplit = searchTerm.replace(/ /g, "'):containsi('")
//
//                $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
//                    return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
//                }
//                });
//
//                $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
//                    $(this).attr('visible','false');
//                });
//
//                $(".results tbody tr:containsi('" + searchSplit + "')").each(function(e){
//                    $(this).attr('visible','true');
//                });
//
//                var jobCount = $('.results tbody tr[visible="true"]').length;
//                $('.counter').text(jobCount + ' item');
//
//                if(jobCount == '0') {$('.no-result').show();}
//                else {$('.no-result').hide();}
//            });
            var table = $('#ecuesTable').DataTable({
                dom:'Blfrtip',
                buttons:[
                    'copy', 'excel', 'pdf'
                ],
                "columnDefs":[
                    {"orderable":false, "targets":5}
                ]
            });

            table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container() ))
    </script>

@endsection

@section('css')

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/datatables.min.css"/>

    {{--<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css">--}}
    {{--<style>--}}
        {{--.results tr[visible='false'], .no-result{--}}
            {{--display: none;--}}
        {{--}--}}
        {{--.results tr[visible='true']{--}}
            {{--display: table-row;--}}
        {{--}--}}
        {{--.counter{--}}
            {{--padding: 8px;--}}
            {{--color: #acacac;--}}
        {{--}--}}
    {{--</style>--}}
@endsection

resources/views/ecues/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ecue
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ecues.show_fields')
                    <a href="{!! route('ecues.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ecues/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $ecue->id !!}</p>
</div>

<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <p>{!! $ecue->title !!}</p>
</div>

<!-- Semestre Id Field -->
<div class="form-group">
    {!! Form::label('semestre_id', 'Semestre Id:') !!}
    <p>{!! $ecue->semestre_id !!}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'Slug:') !!}
    <p>{!! $ecue->slug !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $ecue->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $ecue->updated_at !!}</p>
</div>

resources/views/ecues/table.blade.php
<table class="table table-responsive results" id="ecuesTable">
    <thead>
        <tr>
            <th>Title</th>
            <th>Semestre</th>
            <th>Slug</th>
            <th>Specialites</th>
            <th>Année académique</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($ecues as $ecue)
        <tr>
            <td>{!! $ecue->title !!}</td>
            <td>{!! $ecue->semestre->title !!}</td>
            <td>{!! $ecue->slug !!}</td>
            <td>
                <div class="label-group">
                    @foreach($ecue->specialites as $specialite)
                        <label>{!! '   '.$specialite->slug . $ecue->semestre->cycle->niveau!!}   </label>
                    @endforeach
                </div>
            </td>
            <td>{!! $ecue->academicYear->debut. '/'. $ecue->academicYear->fin !!}</td>

            <td>
                {!! Form::open(['route' => ['ecues.destroy', $ecue->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('ecues.show', [$ecue->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('ecues.edit', [$ecue->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>