routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::prefix('admin')->namespace('Back')->group(function () { 
    Route::name('admin')->get('/', 'AdminController@index');
});
Route::prefix('')->middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('home', 'HomeController@index');
    Route::get('absences/updateJustif/{justification}/{absence}', ['middleware' => 'permission:edit absences', 'uses' => 'AbsenceController@justif'])->name('absences.updateJustif');

    Route::get('absences/updateJustif/{justification}/{absence}', ['middleware' => 'permission:edit absences', 'uses' => 'AbsenceController@updateJustif'])->name('absences.updateJustif');

    Route::get('absences/search/{n}', ['middleware' => 'permission:create absences|read absences|read enseignements', 'uses' => 'AbsenceController@search'])->name('absences.search');
    Route::get('absences/etat', 'AbsenceController@etat')->name('absences.etat');

    Route::get('absences/affiche/{semestre}/{specialite}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@affiche'])->name('absences.affiche');

    Route::get('absences/afficheDouala/{semestre}/{specialite}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@afficheDouala'])->name('absences.afficheDouala');

    Route::get('absences/afficheYaounde/{semestre}/{specialite}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@afficheYaounde'])->name('absences.afficheYaounde');

    Route::get('absences/create/{semestre}/{specialite}', ['middleware' => 'permission:create absences', 'uses' => 'AbsenceController@create'])->name('absences.create');

    Route::get('absences/createDouala/{semestre}/{specialite}', ['middleware' => 'permission:create absences', 'uses' => 'AbsenceController@createDouala'])->name('absences.createDouala');

    Route::get('absences/createYaounde/{semestre}/{specialite}', ['middleware' => 'permission:create absences', 'uses' => 'AbsenceController@createYaounde'])->name('absences.createYaounde');

    Route::get('absences/ficheDouala/{semestre}/{specialite}', 'AbsenceController@ficheDouala')->name('absences.ficheDouala');

    Route::get('absences/ficheDouala/{semestre}/{specialite}/{id}', 'AbsenceController@ficheEcueDouala')->name('absences.fiche-ecue-douala');

    Route::get('absences/ficheYaounde/{semestre}/{specialite}', 'AbsenceController@ficheYaounde')->name('absences.ficheYaounde');

    Route::get('absences/ficheYaounde/{semestre}/{specialite}/{id}', 'AbsenceController@ficheEcueYaounde')->name('absences.fiche-ecue-yaounde');

    Route::get('absences/{apprenant}/edit/{semestre}', ['middleware' => 'permission:read absences', 'uses' => 'AbsenceController@edit'])->name('absences.edit');

    //    Route::get('absence/afficheData, AbsenceController@afficheData')->name('absences.afficheData');
    Route::resource('absences', 'AbsenceController')->except('create', 'edit', 'show');

    Route::name('specialites.getData')->get('specialites/getData', 'SpecialiteController@getData');

    Route::resource('semestres', 'SemestreController');

    Route::get('contrats/all', 'ContratController@all')->name('contrats.all');
    Route::resource('contrats', 'ContratController');

    Route::get('ecues/{id}/getEcues', 'EcueController@getEcues');
    Route::resource('ecues', 'EcueController');

    Route::resource('cycles', 'CycleController');

    Route::resource('apprenants', 'ApprenantController');

    Route::resource('specialites', 'SpecialiteController');

    Route::resource('enseignants', 'EnseignantController');

    Route::get('tutors/{id}', 'TutorController@index')->name('tutors.index');
    Route::get('tutors/create/{id}', 'TutorController@create')->name('tutors.create');
    Route::post('tutors/{id}', 'TutorController@store')->name('tutors.store');
    Route::resource('tutors', 'TutorController')->only('edit', 'update', 'destroy');

    Route::resource('enseignements', 'EnseignementController')->except('create');
    Route::get('enseignements/affiche/{semestre}/{specialite}', 'EnseignementController@affiche')->name('enseignements.affiche');
    Route::get('enseignements/afficheDouala/{semestre}/{specialite}', 'EnseignementController@afficheDouala')->name('enseignements.afficheDouala');
    Route::get('enseignements/afficheYaounde/{semestre}/{specialite}', 'EnseignementController@afficheYaounde')->name('enseignements.afficheYaounde');

    Route::get('enseignements/search/{n}', 'EnseignementController@search')->name('enseignements.search');
    Route::patch('enseignements/{specialites}/updateMh', 'EnseignementController@updateMh')->name('enseignements.updateMh');
    Route::get('enseignements/{specialite}/editMh', 'EnseignementController@editMh')->name('enseignements.editMh');
    Route::get('enseignements/create/{semestre}/{specialite}', 'EnseignementController@create')->name('enseignements.create');
    Route::get('enseignements/rapport/{n}', 'EnseignementController@rapport')->name('rapport');

    // Afficher les fiches d'autorisation de paiement
    Route::get('enseignements/autorisation-paiement/{id}', 'EnseignementController@autorisationPaiement')->name('enseignements.autorisation-paiement');

    //    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('users', 'UserController');

    Route::get('absences/test', 'AbsenceController@test');

    Route::resource('catUes', 'CatUeController')->except('show');
    Route::resource('ues', 'UeController')->except('show');

    Route::get('notes/search/{n}/{type?}', 'NoteController@search')->name('notes.search');
    // Routes pour l'enregistrement des notes
    Route::get('notes/affiche/{semestre}/{specialite}', 'NoteController@affiche')->name('notes.affiche');
    Route::get('notes/afficheNotesDouala/{semestre}/{specialite}', 'NoteController@afficheNotesDouala')->name('notes.afficheNotesDouala');
    Route::get('notes/afficheNotesYaounde/{semestre}/{specialite}', 'NoteController@afficheNotesYaounde')->name('notes.afficheNotesYaounde');

    Route::get('notes/imprime/{semestre}/{specialite}', 'NoteController@imprime')->name('notes.imprime');
    Route::get('notes/releve/{session}/{contrat}/{semestre}', 'NoteController@releve')->name('notes.releve');
    Route::get('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@a_deliberer')->name('notes.a_deliberer');
    Route::post('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@pv')->name('notes.pv');

    Route::get('notes/pvcc/{specialite}/{semestre}', 'NoteController@pvcc')->name('notes.pvcc');
    Route::get('notes/pvccDla/{specialite}/{semestre}', 'NoteController@pvcc_dla')->name('notes.pvcc_dla');
    Route::get('notes/pvccYde/{specialite}/{semestre}', 'NoteController@pvcc_yde')->name('notes.pvcc_yde');

    Route::get('notes/rn_intermediaire/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaire')->name('notes.rn_intermediaire');
    Route::get('notes/rn_intermediaireDouala/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireDouala')->name('notes.rn_intermediaireDouala');
    Route::get('notes/rn_intermediaireYaounde/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireYaounde')->name('notes.rn_intermediaireYaounde');

    Route::resource('notes', 'NoteController')->except('store', 'show');

    Route::get('notes/show/{type}/{id}', 'NoteController@show')->name('notes.show');
    Route::get('notes/showDouala/{type}/{id}', 'NoteController@showDouala')->name('notes.showDouala');
    Route::get('notes/showYaounde/{type}/{id}', 'NoteController@showYaounde')->name('notes.showYaounde');
    
    Route::post('notes/{type}/{enseignement}', 'NoteController@store')->name('notes.store');
    // Enregistrer les notes de Douala
    Route::post('notes1/{type}/{enseignement}', 'NoteController@storeDouala')->name('notes.storeDouala');
    // Enregistrer les notes de Yaoundé
    Route::post('notes2/{type}/{enseignement}', 'NoteController@storeYaounde')->name('notes.storeYaounde');

    

    Route::get('notes/deliberation/{semestre}/{specialite}', 'NoteController@deliberation')->name('notes.deliberation');
    Route::get('notes/notesDeliberation/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberation')->name('notes.noteDeliberation');
    // Enregistrer la note de délibération
    Route::post('notes/deliberation/{semestre}/{type}/{contrat}', 'NoteController@saveDeliberation')->name('notes.saveDeliberation');
    /*
        Séparer les notes de délibération de Douala et Yaoundé
        Route::get('notes/deliberationDouala/{semestre}/{specialite}', 'NoteController@deliberationDouala')->name('notes.deliberationDouala');
        Route::get('notes/notesDeliberationDouala/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationDouala')->name('notes.noteDeliberationDouala');

        Route::get('notes/deliberationYaounde/{semestre}/{specialite}', 'NoteController@deliberationYaounde')->name('notes.deliberationYaounde');
        Route::get('notes/notesDeliberationYaounde/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationYaounde')->name('notes.noteDeliberationYaounde');
    */

    Route::get('notes/getNoteContrat/{contrat}/{enseignement}', 'NoteController@getNoteContrat')->name('notes.getNoteContrat');

    Route::get('notes/rattrapage/{semestre}/{specialite}', 'NoteController@rattrapage')->name('notes.rattrapage');
    // Routes fiche de notation Douala

resources/views/categoriesUe/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="content col-md-10">
        <h1>{{ __('Creation de Categorie UE') }}</h1>

        <div class="clearfix"></div>
        @include('flash::message')
        <div class="clearfix"></div>

        <div class="box box-primary">
            {{ Form::open(['route' => 'catUes.store']) }}
            <div class="box-body">

                <div class="form-group col-sm-8">
                    {!! Form::label('title', 'Titre :') !!}
                    {!! Form::text('title', null, ['class' => 'form-control']) !!}
                </div>

                <div class="form-group col-sm-12">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                    <a href="{!! route('catUes.index') !!}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/categoriesUe/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="content col-md-10">
        <h1>{{ __('Modifier Categorie UE') }}</h1>

        <div class="clearfix"></div>
        @include('flash::message')
        <div class="clearfix"></div>

        <div class="box box-primary">
            {{ Form::open(['route' => ['catUes.update', $catUe], 'method' => 'patch']) }}
            <div class="box-body">

                <div class="form-group col-sm-8">
                    {!! Form::label('title', 'Titre :') !!}
                    {!! Form::text('title', $catUe->title, ['class' => 'form-control']) !!}
                </div>

                <div class="form-group col-sm-12">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                    <a href="{!! route('catUes.index') !!}" class="btn btn-default">Cancel</a>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>

@endsection

resources/views/categoriesUe/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="content col-md-10">
        <h1>{{ __('Liste des categories d\'unité d\'enseignement') }}</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('catUes.create') !!}">Ajouter</a>
        </h1>
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="box box-primary">
            <div class="box-body">
                <table id="catUe-table" class="table table-bordered table-stripped">
                    <thead>
                        <tr>
                            <th class="col-md-9">Titre</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                    @foreach($catUes as $catUe)
                        <tr>
                            <td>{{ $catUe->title }}</td>
                            <td>
                                <div class='btn-group pull-right'>
                                    <a href="{!! route('catUes.edit', [$catUe->id]) !!}" class='btn btn-primary btn-sm '>Modifier <i class="glyphicon glyphicon-edit"></i></a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/datatables.min.css"/>
@endsection

@section('scripts')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/datatables.min.js"></script>
    <script type="text/javascript">
        var table = $('#catUe-table').DataTable({
            dom:'Bfrtip',
            buttons:[
                'copy', 'excel', 'pdf'
            ]
        });

        table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container() ))
    </script>
@endsection