routes/web.php
    Route::resource('catUes', 'CatUeController')->except('show');
    Route::resource('ues', 'UeController')->except('show');

    Route::get('notes/search/{n}/{type?}', 'NoteController@search')->name('notes.search');
    // Routes pour l'enregistrement des notes
    Route::get('notes/affiche/{semestre}/{specialite}', 'NoteController@affiche')->name('notes.affiche');
    Route::get('notes/afficheNotesDouala/{semestre}/{specialite}', 'NoteController@afficheNotesDouala')->name('notes.afficheNotesDouala');
    Route::get('notes/afficheNotesYaounde/{semestre}/{specialite}', 'NoteController@afficheNotesYaounde')->name('notes.afficheNotesYaounde');

    Route::get('notes/imprime/{semestre}/{specialite}', 'NoteController@imprime')->name('notes.imprime');
    Route::get('notes/releve/{session}/{contrat}/{semestre}', 'NoteController@releve')->name('notes.releve');
    Route::get('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@a_deliberer')->name('notes.a_deliberer');
    Route::post('notes/pv/{specialite}/{semestre}/{type?}', 'NoteController@pv')->name('notes.pv');

    Route::get('notes/pvcc/{specialite}/{semestre}', 'NoteController@pvcc')->name('notes.pvcc');
    Route::get('notes/pvccDla/{specialite}/{semestre}', 'NoteController@pvcc_dla')->name('notes.pvcc_dla');
    Route::get('notes/pvccYde/{specialite}/{semestre}', 'NoteController@pvcc_yde')->name('notes.pvcc_yde');

    Route::get('notes/rn_intermediaire/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaire')->name('notes.rn_intermediaire');
    Route::get('notes/rn_intermediaireDouala/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireDouala')->name('notes.rn_intermediaireDouala');
    Route::get('notes/rn_intermediaireYaounde/{specialite}/{semestre}/{type?}', 'NoteController@rn_intermediaireYaounde')->name('notes.rn_intermediaireYaounde');

    Route::resource('notes', 'NoteController')->except('store', 'show');

    Route::get('notes/show/{type}/{id}', 'NoteController@show')->name('notes.show');
    Route::get('notes/showDouala/{type}/{id}', 'NoteController@showDouala')->name('notes.showDouala');
    Route::get('notes/showYaounde/{type}/{id}', 'NoteController@showYaounde')->name('notes.showYaounde');
    
    Route::post('notes/{type}/{enseignement}', 'NoteController@store')->name('notes.store');
    // Enregistrer les notes de Douala
    Route::post('notes1/{type}/{enseignement}', 'NoteController@storeDouala')->name('notes.storeDouala');
    // Enregistrer les notes de Yaoundé
    Route::post('notes2/{type}/{enseignement}', 'NoteController@storeYaounde')->name('notes.storeYaounde');

    

    Route::get('notes/deliberation/{semestre}/{specialite}', 'NoteController@deliberation')->name('notes.deliberation');
    Route::get('notes/notesDeliberation/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberation')->name('notes.noteDeliberation');
    // Enregistrer la note de délibération
    Route::post('notes/deliberation/{semestre}/{type}/{contrat}', 'NoteController@saveDeliberation')->name('notes.saveDeliberation');
    /*
        Séparer les notes de délibération de Douala et Yaoundé
        Route::get('notes/deliberationDouala/{semestre}/{specialite}', 'NoteController@deliberationDouala')->name('notes.deliberationDouala');
        Route::get('notes/notesDeliberationDouala/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationDouala')->name('notes.noteDeliberationDouala');

        Route::get('notes/deliberationYaounde/{semestre}/{specialite}', 'NoteController@deliberationYaounde')->name('notes.deliberationYaounde');
        Route::get('notes/notesDeliberationYaounde/{type}/{contrat}/{semestre}', 'NoteController@noteDeliberationYaounde')->name('notes.noteDeliberationYaounde');
    */

    Route::get('notes/getNoteContrat/{contrat}/{enseignement}', 'NoteController@getNoteContrat')->name('notes.getNoteContrat');

    Route::get('notes/rattrapage/{semestre}/{specialite}', 'NoteController@rattrapage')->name('notes.rattrapage');
    // Routes fiche de notation Douala
    Route::get('notes/fiche/{semestre}/{specialite}', 'NoteController@fiche')->name('notes.fiche');
    Route::get('notes/fiche/{semestre}/{specialite}/{id}', 'NoteController@ficheNotationCC')->name('notes.fiche-notation');

    // Routes fiche de notation Yaoundé
    Route::get('notes/ficheYaounde/{semestre}/{specialite}', 'NoteController@ficheYaounde')->name('notes.ficheYaounde');
    Route::get('notes/ficheYaounde/{semestre}/{specialite}/{id}', 'NoteController@ficheNotationCCYaounde')->name('notes.fiche-notation-yaounde');

    Route::get('versements/listeApprenants', 'VersementController@listeApprenants')->name('versements.listeApprenants');
    Route::get('versements/etats', 'VersementController@etats')->name('versements.etats');
    Route::get('versements/details/{id}', 'VersementController@details')->name('versements.details');
    Route::post('versements/{id}', 'VersementController@store')->name('versements.store');
    Route::get('versements/show/{id}', 'VersementController@show')->name('versements.show');
    Route::get('versements/{id}/edit', 'VersementController@edit')->name('versements.edit');
    Route::patch('versements/{id}/update', 'VersementController@update')->name('versements.update');
    Route::delete('versements/destroy/{id}', 'VersementController@destroy')->name('versements.destroy');


    Route::resource('echeanciers', 'EcheancierController');

    Route::get('moratoires/create/{id}', 'MoratoireController@create')->name('moratoires.create');
    Route::post('moratoires/{id}', 'MoratoireController@store')->name('moratoires.store');
    Route::get('moratoires', 'MoratoireController@index')->name('moratoires.index');
    Route::get('moratoires/{id}/edit', 'MoratoireController@edit')->name('moratoires.edit');
    Route::patch('moratoires/{id}', 'MoratoireController@update')->name('moratoires.update');

    Route::get('scolarites', 'ScolariteController@index')->name('scolarites.index');
    Route::get('scolarites/old', 'ScolariteController@old')->name('scolarites.old');
    Route::get('scolarites/inscrits', 'ScolariteController@inscrits')->name('scolarites.inscrits');
    Route::post('scolarites/filter', 'ScolariteController@filter')->name('scolarites.filter');

    Route::get('rnr', function () {
        return view('notes.rnr_imprime');
    });
    Route::get('certificat/{type}', function ($type) {
        return view('documents.certificat')->with(['type' => $type]);
    });
    Route::get('scolarites/contrats/{id}', 'ScolariteController@contrats')->name('scolarites.contrat');
    Route::get('scolarites/attestation/{contrat}/{type}', 'ScolariteController@attestation')->name('scolarites.attestation');
    Route::get('scolarites/certificat/{contrat}/{type}', 'ScolariteController@certificat')->name('scolarites.certificat');
    Route::get('scolarites/autorisation/{id}', 'ScolariteController@autorisation')->name('scolarites.autorisation');
    Route::get('scolarites/suspension/{id}', 'ScolariteController@suspension')->name('scolarites.suspension');
    Route::get('scolarites/printSuspension', 'ScolariteController@printSuspension')->name('scolarites.printSuspension');
    Route::post('scolarites/printSuspension', 'ScolariteController@suspensions')->name('scolarites.suspensions');

    Route::get('scolarites/attestations/search/{n}', 'ScolariteController@search')->name('scolarites.search'); // pour selectionner la classe a imprimer
    Route::get('scolarites/attestations/select/{cycle}/{specialite}', 'ScolariteController@select_admis')->name('scolarites.select_admis');
    Route::post('scolarites/attestations_reussite', 'ScolariteController@attestations_reussite')->name('scolarites.attestations_reussite');

    Route::get('resultatNominatifs/search/{n}', 'ResultatNominatifController@search')->name('resultatNominatifs.search');
    Route::get('resultatNominatifs/create/{specialite}/{cycle}', 'ResultatNominatifController@create')->name('resultatNominatifs.create');
    Route::post('resultatNominatifs', 'ResultatNominatifController@store')->name('resultatNominatifs.store');

    //    Route::post('notes/{enseignement}/{contrat}', 'NoteController@store')->name('notes.store');

    Route::resource('academicYears', 'AcademicYearController');

    Route::resource('contratEnseignants', 'ContratEnseignantController')->except('show');
    Route::get('contratsEnseignants/all', 'ContratEnseignantController@all')->name('contratEnseignants.all');
    Route::post('contratEnseignants/filter', 'ContratEnseignantController@filter')->name('contratEnseignants.filter');
    Route::get('contratEnseignants/versements/{id}', 'ContratEnseignantController@versements')->name('contratEnseignants.versements');
    Route::post('contratEnseignants/versements/{id}/{type?}', 'ContratEnseignantController@save')->name('contratEnseignants.save');
    Route::get('contratEnseignants/rapport/{id}', 'ContratEnseignantController@rapport')->name('contratEnseignants.rapport');
    Route::get('contratEnseignants/contrats/{id}', 'ContratEnseignantController@contrat')->name('contratEnseignants.contrat');
    Route::get('contratEnseignants/details/{id}', 'ContratEnseignantController@details')->name('contratEnseignants.details');
    Route::get('contratEnseignants/{id}/edit_payment', 'ContratEnseignantController@edit_payment')->name('contratEnseignants.edit_payment');
    Route::delete('contratEnseignants/delete/{id}', 'ContratEnseignantController@delete_payment')->name('contratEnseignants.delete_payment');
    Route::patch('contratEnseignants/update_payment/{id}', 'ContratEnseignantController@update_payment')->name('contratEnseignants.update_payment');



    Route::resource('academicCalendars', 'AcademicCalendarController');

    Route::resource('corkages', 'CorkageController')->except('create');
    Route::get('corkages/create/{id}', 'CorkageController@create')->name('corkages.create');

    // 02/08/2021
    Route::resource('pays', 'PaysController');

app/Models/ContratEnseignant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ContratEnseignant extends Model
{
    protected $fillable = [
        'enseignant_id',
        'academic_year_id',
        'mh_licence',
        'mh_master',
        'rang',
        'ville_id',
    ];

    public static $rules = [
        'montant' => 'bail|required|integer',
        'date' => 'bail|required|date',
        'tranche' => 'bail|required',
        'numero_piece' => 'bail|required',
        'ecue_id' => 'bail|required|integer',
        'specialite' => 'bail|required',
        'ville_id' => 'bail|required|integer',
    ];

    public function enseignant(){
        return $this->belongsTo(Enseignant::class);
    }

    public function academic_year(){
        return $this->belongsTo(AcademicYear::class);
    }

    public function enseignements()
    {
        return $this->hasMany(\App\Models\Enseignement::class);
    }

    public function payments(){
        return $this->hasMany(TeacherPay::class);
//        return $this->morphMany(TeacherPay::class, 'teachable');
    }

    public function ville(){
        return $this->belongsTo(Ville::class);
    }
}

resources/views/contratEnseignants/create.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Contrat D'enseignant
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div>
                    <table class="table table-bordered table-striped" id="apprenants-table">
                        <thead>
                        <tr>
                            <th>Nom et prenom</th>
                            {{--                            <th>Decision</th>--}}
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($enseignants as $enseignant)
                            <tr>
                                <td>{!! $enseignant->name !!}</td>
                                {{--                                <td>{!! (!empty($apprenant->contrats->last()->resultatNominatifs)) ? $apprenant->contrats->last()->resultatNominatifs : '' !!}</td>--}}
                                <td>
                                    <button type="button" class="btn btn-primary" data-toggle="modal"
                                            data-target="#printModal" data-id="{{ $enseignant->id }}"
                                            id="autoriser" title="Contrat de charge d'enseignement">
                                        Autoriser
                                    </button>
                                    
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>  
                </div>
            </div>

            <div class="box-footer text-right">
                <a href="{!! route('contratEnseignants.index') !!}" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </div>

    <div class="modal fade" id="printModal" tabindex="-1" role="dialog" aria-labelledby="printModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                {{Form::open(['route' => 'contratEnseignants.store'])}}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="justificationModalLabel">Infos</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="form-group col-xs-4 doc">
                                {!! Form::label('mh_licence', 'Montant Horaire Licence:') !!}
                                {!! Form::text('mh_licence', null, ['class' => 'form-control']) !!}
                            </div>
                            
                            <div class="form-group col-xs-4 semestre doc">
                                {!! Form::label('mh_master', 'Montant horaire Master:') !!}
                                {!! Form::text('mh_master', null, ['class' => 'form-control']) !!}
                            </div>

                            <div class="form-group col-xs-4">
                                <label class="form-control-label" for="ville_id">Sélectionnez la ville</label>
                                <select id="ville_id" class="form-control" name="ville_id">
                                    @foreach($villes as $ville)
                                        <option value="{{$ville->id}}">{{$ville->nom}}</option>
                                    @endforeach
                                </select>
                            </div>
            
                            <div id="enseignant-id"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close">Close</button>
                        <button class="btn btn-primary" id="send">Save</button>
                    </div>
                {{Form::close()}}
            </div>
        </div>
    </div>

@endsection

@section('scripts')


    

    <script type="text/javascript">
        $(function(){
            $('#printModal').on('show.bs.modal', function(e){
                var button = $(e.relatedTarget);
                var id = button.data('id');
                var input = '<input name="enseignant_id" type="hidden" value="'+ id +'"/>';
                $('#enseignant-id').html(input);
            })
        })
    </script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
        $(function(){
            var table = $('#apprenants-table').DataTable({
                responsive: true,
                dom:'Blfrtip',
                buttons:[
                    'copy', 'excel', 'pdf'
                ],
                "columnDefs":[
                    {"orderable":false, "targets":1}
                ]
            });

        })
    </script>
@endsection

@section('css')

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-3.3.1/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/b-print-1.5.6/datatables.min.css"/>

@endsection

resources/views/contratEnseignants/edit.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Contrat de {{ $contrat->enseignant->nom }}
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div>
                    {!! Form::model($contrat, ['route' => ['contratEnseignants.update', $contrat->id], 'method' => 'patch']) !!}

                    <div class="form-group col-xs-4">
                        {!! Form::label('mh_licence', 'Montant horaire Licence :') !!}
                        {!! Form::text('mh_licence', $contrat->mh_licence, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-xs-4">
                        {!! Form::label('mh_master', 'Montant horaire Master :') !!}
                        {!! Form::text('mh_master', $contrat->mh_master, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-xs-4">
                        {!! Form::label('ville_id', 'Ville :') !!}
                        {!! Form::select('ville_id', [1=>'Douala', 2 => 'Yaounde'], $contrat->ville->nom, ['class' => 'form-control']) !!}
                    </div>
                </div>
            </div>

            <div class="box-footer text-right">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{!! route('contratEnseignants.index') !!}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}
        </div>
    </div>

@endsection

resources/views/contratEnseignants/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Contrats Enseignants</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('contratEnseignants.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="box box-primary">
            <div class="box-body">
                {!! Form::open(['route' => 'contratEnseignants.filter' ]) !!}
                    <div class="form-group col-sm-4">
                        {{ Form::label('year', 'Année académique') }}
                        {!! Form::select('year',$filterYears,null,['class' => 'form-control', 'placeholder' => 'Année académique', 'id'=>'year']) !!}
                    </div>
                    <div class="form-group col-sm-4">
                        {{ Form::label('ville', 'Ville') }}
                        {!! Form::select('ville',$filterVilles,null,['class' => 'form-control', 'placeholder' => 'Ville', 'id'=>'ville']) !!}
                    </div>
                    <div class="form-group col-sm-12">
                        {!! Form::submit('filtrer', ['class' => 'btn btn-primary']) !!}
                        <a href="{!! route('contratEnseignants.index') !!}" class="btn btn-default">Cancel</a>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>

        <div class="box box-primary">
            <div class="box-body">
                <table class="table table-responsive results" id="contrats-table">
                    <thead>
                    <tr>
                        <th>Nom Enseigant</th>
                        <th>Annee Academique</th>
                        <th>Ville</th>
                        <th>Tarif licence</th>
                        <th>Tarif Master</th>
                        <th>Montant total</th>
                        <th>Montant à payé</th>
                        <th>Montant versé</th>
                        <th>Montant restant</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($contrats as $contrat)
                        @if(isset($contrat->enseignant))
                        <tr>
                            <td>{{ $contrat->enseignant->name }}</td>
                            <td>{{ $contrat->academic_year->debut. '/' .$contrat->academic_year->fin }}</td>
                            <td>{{ !empty($contrat->ville) ? $contrat->ville->nom:'' }}</td>
                            <td>{{ $contrat->mh_licence }}</td>
                            <td>{{ $contrat->mh_master }}</td>
                            <td id="{{ 'total-'. $contrat->id }}"></td>
                            <td id="{{ 'du-'. $contrat->id }}"></td>
                            <td id="{{ 'verse-'. $contrat->id }}"></td>
                            <td id="{{ 'rest-'. $contrat->id }}"></td>
                            <td>
                                @can('edit teachers contract')
                                    <a href="{!! route('contratEnseignants.edit', [$contrat->id]) !!}" class='btn btn-default btn-xs' title="editer le contrat de l'enseignant"><i class="glyphicon glyphicon-edit"></i></a>
                                @endcan
                                @can('read teachers contract')
                                    <a href="{!! route('contratEnseignants.rapport', [$contrat->id]) !!}" class='btn btn-info btn-xs' title="voir les versements de l'enseignant"><i class="glyphicon glyphicon-eye-open"></i></a>
                                @endcan
                                @can('delete teachers contract')
                                    <div class='btn-group'>
                                        {!! Form::open(['route' => ['contratEnseignants.destroy', $contrat->id], 'method' => 'delete']) !!}
                                            @can('delete contrats')
                                                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                            @endcan
                                        {!! Form::close() !!}
                                    </div>
                                @endcan
                                @can('print teachers contract')
                                    <a type="button" class="btn btn-warning btn-xs" data-toggle="modal"
                                            data-target="#printModal" data-id="{{ $contrat->id }}"
                                            id="imprimer" title="Contrat de charge d'enseignement">
                                        <i class="glyphicon glyphicon-print"></i>
                                    </a>
{{--                                    <a href="{!! route('contratEnseignants.contrat', [$contrat->id]) !!}" class='btn btn-warning btn-xs' title="Imprimer le contrat"><i class="glyphicon glyphicon-print"></i></a>--}}
                                @endcan
                            </td>
                        </tr>
                        @endif
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td><h4>Total</h4></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong id="total"></strong></td>
                            <td><strong id="nap"></strong></td>
                            <td><strong id="mt_verse"></strong></td>
                            <td><strong id="solde"></strong></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div class="modal fade" id="printModal" tabindex="-1" role="dialog" aria-labelledby="printModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="justificationModalLabel">Imprimer contrat</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="form-group col-xs-6 doc">
                                {!! Form::label('signataire', 'Signataires:') !!}
                                {!! Form::text('signataire', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close">Close</button>
                        <button class="btn btn-primary" id="send">Imprimer</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

@section('scripts')

    <script type="text/javascript">
        $(document).ready(function () {
            $('#printModal').on('show.bs.modal', function(e){
                var button = $(e.relatedTarget);
                var type = button.attr('id');
                var contrat = button.data('id')
                var modal = $(this);

                console.log(contrat)

                $('#send').click(function(e){
                    e.preventDefault();
                    console.log(3)
                    var signataire = $('#signataire').val()

                    var url = 'http://'+ ((window.location.host == 'pigier.test:81') ? window.location.host+'/public' : window.location.host) + '/contratEnseignants/contrats/'+contrat+'?signataire='+signataire;

                    window.open(url,'_blank', 'menubar=no, toolbar=no, width=1000px, height=600px')
                    window.location.reload();
                });
                console.log(window.location.host)
            });
        })
    </script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    {{--<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jq-3.3.1/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/b-print-1.5.6/datatables.min.js"></script>--}}
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.22/b-1.6.5/b-html5-1.6.5/b-print-1.6.5/datatables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.22/api/sum().js"></script>
    <script>

            $(function() {

                @foreach($contrats as $contrat)
                    var total = 0
                    var mh = 0

                    @foreach($enseignements[$contrat->id] as $enseignement)
                        mh = parseInt('{{ ($enseignement->mhTotal < $enseignement->mhEff) ? $enseignement->mhTotal : $enseignement->mhEff }}')
                        total += (parseInt('{{ (int)(($enseignement->ecue->semestre->cycle->label == 'Licence') ? $contrat->mh_licence : $contrat->mh_master) }}') * mh)
                    @endforeach
                    var du = total * (1 - 0.055)
                    var verse = parseInt('{{ (!empty($contrat->payments)) ? $contrat->payments->sum('montant') : 0 }}')
                    var rest = du - verse

                    $('#'+'{{ 'total-'.$contrat->id }}').html(total)
                    $('#'+'{{ 'du-'.$contrat->id }}').html(du)
                    $('#'+'{{ 'verse-'.$contrat->id }}').html(verse)
                    $('#'+'{{ 'rest-'.$contrat->id }}').html(rest)
                @endforeach

                var table = $('#contrats-table').DataTable({
                    responsive: true,
                    dom:'Blfrtip',
                    // buttons:[
                    //     'copy', 'excel', 'pdf'
                    // ],
                    "columnDefs":[
                        {"orderable":false, "targets":8}
                    ]
                });

                var total = table.column(4).data().sum();
                var nap = table.column(5).data().sum();
                var mt_verse = table.column(6).data().sum();
                var solde = table.column(7).data().sum();

                $('#total').html(total)
                $('#nap').html(nap)
                $('#mt_verse').html(mt_verse)
                $('#solde').html(solde)
            });

            // table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container() ))

    </script>

@endsection

@section('css')

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-3.3.1/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/b-print-1.5.6/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/ju/dt-1.10.22/b-1.6.5/b-html5-1.6.5/b-print-1.6.5/datatables.min.css"/>

    {{--<script type="text/javascript" src="https://cdn.datatables.net/v/ju/dt-1.10.22/b-1.6.5/b-html5-1.6.5/b-print-1.6.5/datatables.min.js"></script>--}}

@endsection